Traceback (most recent call last):
  File "Exercise5.py", line 76, in <module>
    h1=np.dot(W1,X_train)+b1
ValueError: shapes (3,22000) and (22000,32,32) not aligned: 22000 (dim 1) != 32 (dim 1)
